# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e7e2710da417f9ff382a213c18b5fe46c9a6899f2e9d97d02b601fe4062cd399d5413ec1cabca3dd6f4bdb4e5b6272611e483e0b3956688499c5fe1876048da

test:
  secret_key_base: d72bc25573ef578f163485db8286e086f8ad6c4033cc11dbab6d726368145fa60c517a34859b37c937aca0ac4e475f9ecc787775d84ff48498fb91e6f2e8268a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
